[package]
name = "gA-V"
version = "0.1.0"
edition = "2021"

[dependencies]
yara-x = "1.12.0"
actix-web = "4"
tokio = { version = "1", features = ["full"] }
sha2 = "0.10"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"